server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd_pedido_dev
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mensaje:
  texto: Configuración obtenida desde Config Server para Pedido Service
